### ISSUE TITLE
System env vars missing for functions

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#10]
Functions should have the following variables (same as Hasura)

- `HASURA_GRAPHQL_ADMIN_SECRET`
- `HASURA_GRAPHQL_JWT_SECRET`

**Comment by mrinalwahal** [comment]
I'm able to use both these environment variables inside my JS/TS functions. Weird!

Maybe try this again when I pushed the next release? Should be `v1.0-internal-15`.

I'll keep this issue open until you close it.

**Comment by elitan** [comment]
Yep, they are back now. All good!
