### ISSUE TITLE
auth env vars

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#13]
1. `AUTH_SERVER_URL` should be set to `http://localhost:${port}/v1/auth`
2. `AUTH_CLIENT_URL` should be configurable via `config.yaml` and should default to `http://localhost:3000`

**Comment by mrinalwahal** [comment]
Is there any specific requirement to send `AUTH_SERVER_URL` to `http://localhost:${port}/v1/auth`?

The current design of the CLI doesn't allow me to do this. I'll have to change stuff.

For 2nd point - I'll get that done when I re-write the config.yaml environment variables altogether.

**Comment by elitan** [comment]
`AUTH_SERVER_URL` must be set to the public endpoint (`/v1/auth`) because otherwise, the OAuth providers do not work. 

https://github.com/nhost/hasura-auth/blob/main/src/routes/signin/providers/utils.ts#L265

**Comment by mrinalwahal** [comment]
Done. This will be out in `v1.0-internal-24`.

**Comment by elitan** [comment]
Awesome! Looking forward to that release! :D
