### ISSUE TITLE
Healthcheck fails after restarting `nhost dev`

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#16]
The health checks for the services work the first time I run `nhost dev`. But if I stop (cmd+c) all services and restart `nhost dev` the health checks fail.

I have to do `nhost down` before running `nhost dev` to make the health checks work again.

**Comment by mrinalwahal** [comment]
I think this has been fixed in v >= 20. Please check it again and close this issue if it's solved for you.

**Comment by elitan** [comment]
Yes. Works.
