### ISSUE TITLE
CLI login and tokens

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#18]
# Login

`/custom/cli/login`

Paramters:

- email
- password

Response:

- id
- token

Save id and token in `~/.nhost.json`

# user

`/custom/cli/user`

Parameters

- id
- token

Response

- id
- workspaces
  - id
  - name
    - apps
      - id
      - name
      - [app settings for hasura, auth, storage]
      - envVars
        - key
        - value

**Comment by mrinalwahal** [comment]
Looks good. Let me know when you have created these endpoints.

Maybe we can make the user endpoint as `/custom/cli/{user_id}`. Add the user ID directly to URL. I'll pass the token in body.

**Comment by mrinalwahal** [comment]
Can you also return me username for the user, team slugs and project slugs in the response payload?

Currently we are closing remote projects with `nhost init -r {project_name}`.

But this is bad logic. For following reasons:

- Multiple personal projects can have same name.
- Multiple team projects can have same name.
- Both a team project, as well as a personal project, can have an identical name.
- This approach doesn't allow us to clone team projects while avoiding the selection prompt.

I want to change this approach to `nhost init -r {team_slug}/{project-slug}`.

To clone a personal project, use: `nhost init -r {project_slug}` OR `nhost init -r {username}/{project_slug}`

To clone a team project, use: `nhost init -r {team_slug}/{project_slug}`

Do let me know what you think!

**Comment by sangdth** [comment]
I login by GitHub but it stills ask only password.

**Comment by mrinalwahal** [comment]
Hey @sangdth, this CLI is not yet released. Please don't use this issue thread.

DM us on discord and we'll help you out.

**Comment by sangdth** [comment]
Thank @mrinalwahal , my bad. I will wait then, please ignore the comment.
