### ISSUE TITLE
--port options on `nhost dev` does not work correctly

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#23]
- functions seems to go to the default port environment (1337)
- auth does not work
- 
https://www.loom.com/share/85ad86b7299b47cbbcd8dd2718e76846

**Comment by elitan** [comment]
Update: I actually had a `nhost dev --port 1338` running when trying this command.

If I have `nhost dev --port 1338` running and I try to do the same command in another environment it should stop right away and tell me port 1338 is already in use.

The functions issue is still there though.

**Comment by mrinalwahal** [comment]
Gotcha. Will make this quick change!
