### ISSUE TITLE
req.query parameters does not work

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#5]
Try this code:

```js
module.exports = (req, res) => {
  console.log(req.query);

  const name = req.query.name;

  res.send(`Hello ${name}!`);
};
```

even if adding `?name=johan` `name` is still undefined.

**Comment by mrinalwahal** [comment]
<img width="1017" alt="Screenshot 2021-09-11 at 3 21 47 AM" src="https://user-images.githubusercontent.com/9859731/132921490-8a3d07f7-2514-442b-8238-3f6b67452328.png">

This issue has been fixed. You can test it in release >= `v1.0-internal-15`.

Please close this issue once you have tested it.

**Comment by elitan** [comment]
Works!
