### ISSUE TITLE
Add HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS in config.yaml

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#6]
I want to be able to toggle `HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS` (`true`/`false`).

Can we add `enable_remote_schema_permissions` under `hasura` in `config.yaml`?

**Comment by mrinalwahal** [comment]
This is done. I'm closing this issue.
